version: "3.7"

services:
    dotnetangular:
        image: dummy11/myappcontainer:2.0.0
        build:
            context: .
            dockerfile: dockerfile
            args:
                ANGULAR_ENVIRONMENT: Development
                ASPNETCORE_ENVIRONMENT: Development
        container_name: helloangular 
        ports:
            - "8095:80"
        
